name: Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies for documentation
      - name: Install MkDocs and dependencies
        run: |
          pip install --upgrade pip
          pip install .[docs]  # Install documentation dependencies defined in pyproject.toml

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --config-file docs/mkdocs.yml --force
